// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/colibri/v1/ratelimiter.proto

package colibri

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRateLimitRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Cbs                  int64    `protobuf:"varint,3,opt,name=cbs,proto3" json:"cbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRateLimitRequest) Reset()         { *m = AddRateLimitRequest{} }
func (m *AddRateLimitRequest) String() string { return proto.CompactTextString(m) }
func (*AddRateLimitRequest) ProtoMessage()    {}
func (*AddRateLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{0}
}

func (m *AddRateLimitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRateLimitRequest.Unmarshal(m, b)
}
func (m *AddRateLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRateLimitRequest.Marshal(b, m, deterministic)
}
func (m *AddRateLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRateLimitRequest.Merge(m, src)
}
func (m *AddRateLimitRequest) XXX_Size() int {
	return xxx_messageInfo_AddRateLimitRequest.Size(m)
}
func (m *AddRateLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRateLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRateLimitRequest proto.InternalMessageInfo

func (m *AddRateLimitRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *AddRateLimitRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *AddRateLimitRequest) GetCbs() int64 {
	if m != nil {
		return m.Cbs
	}
	return 0
}

type Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{1}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

type SetBurstSizeRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Cbs                  int64    `protobuf:"varint,2,opt,name=cbs,proto3" json:"cbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBurstSizeRequest) Reset()         { *m = SetBurstSizeRequest{} }
func (m *SetBurstSizeRequest) String() string { return proto.CompactTextString(m) }
func (*SetBurstSizeRequest) ProtoMessage()    {}
func (*SetBurstSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{2}
}

func (m *SetBurstSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBurstSizeRequest.Unmarshal(m, b)
}
func (m *SetBurstSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBurstSizeRequest.Marshal(b, m, deterministic)
}
func (m *SetBurstSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBurstSizeRequest.Merge(m, src)
}
func (m *SetBurstSizeRequest) XXX_Size() int {
	return xxx_messageInfo_SetBurstSizeRequest.Size(m)
}
func (m *SetBurstSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBurstSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBurstSizeRequest proto.InternalMessageInfo

func (m *SetBurstSizeRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *SetBurstSizeRequest) GetCbs() int64 {
	if m != nil {
		return m.Cbs
	}
	return 0
}

type SetRateRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRateRequest) Reset()         { *m = SetRateRequest{} }
func (m *SetRateRequest) String() string { return proto.CompactTextString(m) }
func (*SetRateRequest) ProtoMessage()    {}
func (*SetRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{3}
}

func (m *SetRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRateRequest.Unmarshal(m, b)
}
func (m *SetRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRateRequest.Marshal(b, m, deterministic)
}
func (m *SetRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRateRequest.Merge(m, src)
}
func (m *SetRateRequest) XXX_Size() int {
	return xxx_messageInfo_SetRateRequest.Size(m)
}
func (m *SetRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRateRequest proto.InternalMessageInfo

func (m *SetRateRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *SetRateRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type SetBurstSizeAndRateRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Cbs                  int64    `protobuf:"varint,2,opt,name=cbs,proto3" json:"cbs,omitempty"`
	Rate                 float64  `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBurstSizeAndRateRequest) Reset()         { *m = SetBurstSizeAndRateRequest{} }
func (m *SetBurstSizeAndRateRequest) String() string { return proto.CompactTextString(m) }
func (*SetBurstSizeAndRateRequest) ProtoMessage()    {}
func (*SetBurstSizeAndRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{4}
}

func (m *SetBurstSizeAndRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBurstSizeAndRateRequest.Unmarshal(m, b)
}
func (m *SetBurstSizeAndRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBurstSizeAndRateRequest.Marshal(b, m, deterministic)
}
func (m *SetBurstSizeAndRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBurstSizeAndRateRequest.Merge(m, src)
}
func (m *SetBurstSizeAndRateRequest) XXX_Size() int {
	return xxx_messageInfo_SetBurstSizeAndRateRequest.Size(m)
}
func (m *SetBurstSizeAndRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBurstSizeAndRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBurstSizeAndRateRequest proto.InternalMessageInfo

func (m *SetBurstSizeAndRateRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *SetBurstSizeAndRateRequest) GetCbs() int64 {
	if m != nil {
		return m.Cbs
	}
	return 0
}

func (m *SetBurstSizeAndRateRequest) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type GetterForIdentifierRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetterForIdentifierRequest) Reset()         { *m = GetterForIdentifierRequest{} }
func (m *GetterForIdentifierRequest) String() string { return proto.CompactTextString(m) }
func (*GetterForIdentifierRequest) ProtoMessage()    {}
func (*GetterForIdentifierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{5}
}

func (m *GetterForIdentifierRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetterForIdentifierRequest.Unmarshal(m, b)
}
func (m *GetterForIdentifierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetterForIdentifierRequest.Marshal(b, m, deterministic)
}
func (m *GetterForIdentifierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetterForIdentifierRequest.Merge(m, src)
}
func (m *GetterForIdentifierRequest) XXX_Size() int {
	return xxx_messageInfo_GetterForIdentifierRequest.Size(m)
}
func (m *GetterForIdentifierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetterForIdentifierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetterForIdentifierRequest proto.InternalMessageInfo

func (m *GetterForIdentifierRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type GetBurstSizeResponse struct {
	Cbs                  int64    `protobuf:"varint,1,opt,name=cbs,proto3" json:"cbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBurstSizeResponse) Reset()         { *m = GetBurstSizeResponse{} }
func (m *GetBurstSizeResponse) String() string { return proto.CompactTextString(m) }
func (*GetBurstSizeResponse) ProtoMessage()    {}
func (*GetBurstSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{6}
}

func (m *GetBurstSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBurstSizeResponse.Unmarshal(m, b)
}
func (m *GetBurstSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBurstSizeResponse.Marshal(b, m, deterministic)
}
func (m *GetBurstSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBurstSizeResponse.Merge(m, src)
}
func (m *GetBurstSizeResponse) XXX_Size() int {
	return xxx_messageInfo_GetBurstSizeResponse.Size(m)
}
func (m *GetBurstSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBurstSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBurstSizeResponse proto.InternalMessageInfo

func (m *GetBurstSizeResponse) GetCbs() int64 {
	if m != nil {
		return m.Cbs
	}
	return 0
}

type GetRateResponse struct {
	Rate                 float64  `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRateResponse) Reset()         { *m = GetRateResponse{} }
func (m *GetRateResponse) String() string { return proto.CompactTextString(m) }
func (*GetRateResponse) ProtoMessage()    {}
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{7}
}

func (m *GetRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRateResponse.Unmarshal(m, b)
}
func (m *GetRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRateResponse.Marshal(b, m, deterministic)
}
func (m *GetRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRateResponse.Merge(m, src)
}
func (m *GetRateResponse) XXX_Size() int {
	return xxx_messageInfo_GetRateResponse.Size(m)
}
func (m *GetRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRateResponse proto.InternalMessageInfo

func (m *GetRateResponse) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type GetBurstSizeAndRateResponse struct {
	Cbs                  int64    `protobuf:"varint,1,opt,name=cbs,proto3" json:"cbs,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBurstSizeAndRateResponse) Reset()         { *m = GetBurstSizeAndRateResponse{} }
func (m *GetBurstSizeAndRateResponse) String() string { return proto.CompactTextString(m) }
func (*GetBurstSizeAndRateResponse) ProtoMessage()    {}
func (*GetBurstSizeAndRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b17263e6183a5a21, []int{8}
}

func (m *GetBurstSizeAndRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBurstSizeAndRateResponse.Unmarshal(m, b)
}
func (m *GetBurstSizeAndRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBurstSizeAndRateResponse.Marshal(b, m, deterministic)
}
func (m *GetBurstSizeAndRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBurstSizeAndRateResponse.Merge(m, src)
}
func (m *GetBurstSizeAndRateResponse) XXX_Size() int {
	return xxx_messageInfo_GetBurstSizeAndRateResponse.Size(m)
}
func (m *GetBurstSizeAndRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBurstSizeAndRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBurstSizeAndRateResponse proto.InternalMessageInfo

func (m *GetBurstSizeAndRateResponse) GetCbs() int64 {
	if m != nil {
		return m.Cbs
	}
	return 0
}

func (m *GetBurstSizeAndRateResponse) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRateLimitRequest)(nil), "proto.colibri.v1.AddRateLimitRequest")
	proto.RegisterType((*Success)(nil), "proto.colibri.v1.Success")
	proto.RegisterType((*SetBurstSizeRequest)(nil), "proto.colibri.v1.SetBurstSizeRequest")
	proto.RegisterType((*SetRateRequest)(nil), "proto.colibri.v1.SetRateRequest")
	proto.RegisterType((*SetBurstSizeAndRateRequest)(nil), "proto.colibri.v1.SetBurstSizeAndRateRequest")
	proto.RegisterType((*GetterForIdentifierRequest)(nil), "proto.colibri.v1.GetterForIdentifierRequest")
	proto.RegisterType((*GetBurstSizeResponse)(nil), "proto.colibri.v1.GetBurstSizeResponse")
	proto.RegisterType((*GetRateResponse)(nil), "proto.colibri.v1.GetRateResponse")
	proto.RegisterType((*GetBurstSizeAndRateResponse)(nil), "proto.colibri.v1.GetBurstSizeAndRateResponse")
}

func init() { proto.RegisterFile("proto/colibri/v1/ratelimiter.proto", fileDescriptor_b17263e6183a5a21) }

var fileDescriptor_b17263e6183a5a21 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x41, 0xcf, 0xd2, 0x40,
	0x10, 0xa5, 0x54, 0x25, 0x4c, 0x88, 0x92, 0xc5, 0x03, 0xd6, 0xc4, 0xd4, 0x26, 0x98, 0x1e, 0xb4,
	0x15, 0xbc, 0x7a, 0x01, 0x8d, 0xd5, 0xc4, 0x53, 0x7b, 0x53, 0x0f, 0xd2, 0x76, 0xc0, 0x8d, 0xd0,
	0xc5, 0xdd, 0x2d, 0x07, 0x7f, 0x8f, 0x3f, 0xd4, 0xb4, 0x5f, 0x29, 0x0b, 0x6c, 0x49, 0xc9, 0x77,
	0xea, 0xb4, 0x7d, 0x3b, 0xef, 0xed, 0x9b, 0xb7, 0x0b, 0xce, 0x8e, 0x33, 0xc9, 0xfc, 0x84, 0x6d,
	0x68, 0xcc, 0xa9, 0xbf, 0x9f, 0xfa, 0x7c, 0x29, 0x71, 0x43, 0xb7, 0x54, 0x22, 0xf7, 0xca, 0x9f,
	0x64, 0x58, 0x3e, 0xbc, 0x0a, 0xe3, 0xed, 0xa7, 0xce, 0x77, 0x18, 0xcd, 0xd3, 0x34, 0x5c, 0x4a,
	0xfc, 0x5a, 0x20, 0x43, 0xfc, 0x93, 0xa3, 0x90, 0xe4, 0x05, 0x00, 0x4d, 0x31, 0x93, 0x74, 0x45,
	0x91, 0x8f, 0x0d, 0xdb, 0x70, 0xfb, 0xa1, 0xf2, 0x85, 0x10, 0x78, 0x50, 0x74, 0x1f, 0x77, 0x6d,
	0xc3, 0x35, 0xc2, 0xb2, 0x26, 0x43, 0x30, 0x93, 0x58, 0x8c, 0x4d, 0xdb, 0x70, 0xcd, 0xb0, 0x28,
	0x9d, 0x3e, 0xf4, 0xa2, 0x3c, 0x49, 0x50, 0x08, 0x27, 0x80, 0x51, 0x84, 0x72, 0x91, 0x73, 0x21,
	0x23, 0xfa, 0x17, 0xdb, 0xf2, 0x54, 0x3d, 0xbb, 0xc7, 0x9e, 0x1f, 0xe1, 0x71, 0x84, 0xb2, 0x10,
	0x7c, 0x0f, 0xad, 0x4e, 0x0c, 0x96, 0x2a, 0x67, 0x9e, 0xa5, 0xb7, 0x74, 0xbc, 0x50, 0x55, 0x73,
	0x98, 0x0a, 0xc7, 0x7b, 0xb0, 0x02, 0x94, 0x12, 0xf9, 0x27, 0xc6, 0xbf, 0xd4, 0x8b, 0x5b, 0x72,
	0x38, 0x2e, 0x3c, 0x0d, 0x4e, 0x0c, 0x13, 0x3b, 0x96, 0x89, 0xda, 0x65, 0xe3, 0xe8, 0xc8, 0x04,
	0x9e, 0x04, 0x07, 0x47, 0x2a, 0xd0, 0x41, 0x8e, 0xa1, 0xc8, 0xf9, 0x00, 0xcf, 0x03, 0xdd, 0x96,
	0x9b, 0xfa, 0xea, 0x7c, 0x9b, 0xfd, 0x7b, 0x08, 0xa4, 0x0e, 0x0b, 0xf2, 0x08, 0xf9, 0x9e, 0x26,
	0x48, 0x42, 0x18, 0xa8, 0x29, 0x22, 0x13, 0xef, 0x3c, 0x68, 0x9e, 0x26, 0x65, 0xd6, 0xb3, 0x4b,
	0xd8, 0x21, 0x2f, 0x1d, 0xf2, 0xf3, 0x34, 0x31, 0x95, 0x5e, 0xf2, 0x5a, 0xb3, 0xa6, 0x71, 0x92,
	0xd7, 0x19, 0x24, 0x8c, 0x82, 0x76, 0x0c, 0xcd, 0x73, 0xb4, 0xde, 0x68, 0xd1, 0x4d, 0x36, 0x3b,
	0x1d, 0xb2, 0x82, 0x81, 0x0a, 0xb8, 0x91, 0xee, 0xd5, 0x75, 0x3a, 0x85, 0x27, 0x84, 0x81, 0x6a,
	0x8c, 0x6e, 0x26, 0x9a, 0x13, 0x79, 0xdd, 0xb1, 0x1f, 0xd0, 0xab, 0xa2, 0x76, 0xa3, 0xec, 0x97,
	0x5a, 0xf4, 0x99, 0x33, 0x9f, 0xa1, 0x57, 0x1d, 0x6d, 0x62, 0x6b, 0xc5, 0xb6, 0x9d, 0xec, 0x62,
	0xf6, 0xed, 0xed, 0x9a, 0xca, 0x5f, 0x79, 0xec, 0x25, 0x6c, 0xeb, 0x8b, 0x84, 0xb2, 0xec, 0xee,
	0x76, 0x2c, 0x4b, 0x7f, 0xcd, 0xfc, 0xdd, 0xef, 0xb5, 0x7f, 0x72, 0x61, 0xc6, 0x8f, 0xca, 0xd7,
	0x77, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x93, 0x26, 0xae, 0xee, 0x48, 0x05, 0x00, 0x00,
}
