{
 "title": "Colibri",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CIR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Rate",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "CBS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "Cbs",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Received and dropped [bytes/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(received_bytes{src_isd_as=\"1-ff00:0:110\"}[$__rate_interval])",
     "legendFormat": "Received bytes: AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    },
    {
     "expr": "rate(dropped_bytes_due_to_RL[$__rate_interval])",
     "legendFormat": "Dropped bytes du to RL : AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Output [bytes/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(output_bytes{src_isd_as=\"1-ff00:0:110\"}[$__rate_interval])",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Dropped packets due to duplicate detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "dropped_packets_due_to_DD{src_isd_as=\"1-ff00:0:110\"}",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Dropped [bytes/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(dropped_bytes[$__rate_interval])",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Received [bytes/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(received_bytes[$__rate_interval])",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Rate of dropped packets due to rate limiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(dropped_packets_due_to_RL[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Limiting: dropped [bytes/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(dropped_bytes_due_to_RL[$__rate_interval])",
     "legendFormat": "AS: {{isd_as}},  srcAS: {{src_isd_as}},  egressID: {{egressID}},  ingressID: {{ingressID}}"
    }
   ]
  },
  {
   "title": "Total received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "router_input_pkts_total{neighbor_isd_as=\"1-ff00:0:110\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of reveived packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(router_input_pkts_total{neighbor_isd_as=\"1-ff00:0:110\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "dropped_packets_due_to_RL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of dropped packets ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(router_dropped_pkts_total{neighbor_isd_as=\"1-ff00:0:110\"}[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped packets due to rate limiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "dropped_packets_due_to_RL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of dropped packets due to duplicate detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(dropped_packets_due_to_DD[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "router_dropped_bytes_total{neighbor_isd_as=\"1-ff00:0:110\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output bytes total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "router_output_bytes_total", "legendFormat": "__auto" }
   ]
  }
 ]
}